<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SAG-CVDCSG3" failures="0" tests="3" name="com.webMethodsFlowUI.testsuites.customerdefectsRegressionSuite.CustomerDefectWFL_3205Part2" time="168.350" errors="2" timestamp="20 Jun 2023 07:54:06 GMT">
  <testcase classname="com.webMethodsFlowUI.testsuites.customerdefectsRegressionSuite.CustomerDefectWFL_3205Part2" name="NavigateToDifferentEnvDeployagain" time="61.007">
    <error message="Expected condition failed: waiting for element to no longer be visible: By.xpath: //div[contains(@class,&#039;circle-clipper&#039;)]/div[@class=&#039;circle&#039;] (tried for 60 second(s) with 100 milliseconds interval)
Build info: version: &#039;3.141.59&#039;, revision: &#039;e82be7d358&#039;, time: &#039;2018-11-14T08:17:03&#039;
System info: host: &#039;SAG-CVDCSG3&#039;, ip: &#039;192.168.29.220&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;11.0.19&#039;
Driver info: driver.version: unknown" type="org.openqa.selenium.TimeoutException">
      <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for element to no longer be visible: By.xpath: //div[contains(@class,'circle-clipper')]/div[@class='circle'] (tried for 60 second(s) with 100 milliseconds interval)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'SAG-CVDCSG3', ip: '192.168.29.220', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.19'
Driver info: driver.version: unknown
	at org.openqa.selenium.support.ui.FluentWait.timeoutException(FluentWait.java:304)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:272)
	at com.webMethodsUI.flow.testbase.CommonActions.waitForElementNotVisible(CommonActions.java:268)
	at com.webMethodsUI.flow.pageObjects.common.NavigationMenu.clickOnHomePage(NavigationMenu.java:105)
	at com.webMethodsFlowUI.testsuites.customerdefectsRegressionSuite.CustomerDefectWFL_3205Part2.NavigateToDifferentEnvDeployagain(CustomerDefectWFL_3205Part2.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- NavigateToDifferentEnvDeployagain -->
  <testcase classname="com.webMethodsFlowUI.testsuites.customerdefectsRegressionSuite.CustomerDefectWFL_3205Part2" name="PublishProjectwithSalesforceOauthagain" time="78.508">
    <error message="Expected condition failed: waiting for element to no longer be visible: By.xpath: //div[contains(@class,&#039;circle-clipper&#039;)]/div[@class=&#039;circle&#039;] (tried for 60 second(s) with 100 milliseconds interval)
Build info: version: &#039;3.141.59&#039;, revision: &#039;e82be7d358&#039;, time: &#039;2018-11-14T08:17:03&#039;
System info: host: &#039;SAG-CVDCSG3&#039;, ip: &#039;192.168.29.220&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;11.0.19&#039;
Driver info: driver.version: unknown" type="org.openqa.selenium.TimeoutException">
      <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for element to no longer be visible: By.xpath: //div[contains(@class,'circle-clipper')]/div[@class='circle'] (tried for 60 second(s) with 100 milliseconds interval)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'SAG-CVDCSG3', ip: '192.168.29.220', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.19'
Driver info: driver.version: unknown
	at org.openqa.selenium.support.ui.FluentWait.timeoutException(FluentWait.java:304)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:272)
	at com.webMethodsUI.flow.testbase.CommonActions.waitForElementNotVisible(CommonActions.java:301)
	at com.webMethodsUI.flow.helper.generic.GenericHelper.clickButton(GenericHelper.java:39)
	at com.webMethodsUI.flow.pageObjects.projects.publishprojectpage.ClickingPublishtbutton(publishprojectpage.java:132)
	at com.webMethodsFlowUI.testsuites.customerdefectsRegressionSuite.CustomerDefectWFL_3205Part2.PublishProjectwithSalesforceOauthagain(CustomerDefectWFL_3205Part2.java:78)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- PublishProjectwithSalesforceOauthagain -->
  <testcase classname="com.webMethodsFlowUI.testsuites.customerdefectsRegressionSuite.CustomerDefectWFL_3205Part2" name="loginTest1" time="28.835"/>
</testsuite> <!-- com.webMethodsFlowUI.testsuites.customerdefectsRegressionSuite.CustomerDefectWFL_3205Part2 -->
